#!/bin/bash
# Nonzero exit status aborts commit
# Working directory is repository root

# Only test what is going to be commited
git stash --quiet --keep-index

function cleanup {
	git stash pop --quiet
}

trap cleanup EXIT

branch=$(git branch --show-current)
if test $branch = API; then
	# Test build
	cd API
	dotnet build || { echo API build failed; exit 1; }

	cd ../AuthServer
	dotnet build || { echo AuthServer build failed; exit 1; }
fi
